[FIX] odoo: Fix attribute error
still ``lxml.html.clean``
import is needed because ``lxml.html``
init file don't have clean file. So, it
will be not loaded
https://github.com/lxml/lxml/blob/lxml-4.9/src/lxml/html/__init__.py
```
Traceback (most recent call last):
  File "/tmp/tmpj23nirpw/odoo/19.0/./odoo-bin", line 3, in <module>
    import odoo.cli
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/cli/__init__.py", line 2, in <module>
    from .command import Command, main  # noqa: F401
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/cli/command.py", line 8, in <module>
    import odoo.init  # import first for core setup
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/init.py", line 28, in <module>
    from .tools.gc import gc_set_timing
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/tools/__init__.py", line 11, in <module>
    from .i18n import format_list, py_to_js_locale
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/tools/i18n.py", line 8, in <module>
    from odoo.tools.misc import babel_locale_parse, get_lang
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/tools/misc.py", line 40, in <module>
    from lxml import etree, objectify
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/_monkeypatches/__init__.py", line 45, in exec_module
    patch_module(module.__name__)
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/_monkeypatches/__init__.py", line 67, in patch_module
    module.patch_module()
  File "/tmp/tmpj23nirpw/odoo/19.0/odoo/_monkeypatches/lxml.py", line 14, in patch_module
    lxml.html.clean._find_image_dataurls = re.compile(r'data:image/(.+?);base64,').findall
AttributeError: module 'lxml.html' has no attribute 'clean'
```
https://upgradeci.odoo.com/upgradeci/run/301804

closes odoo/odoo#266722

X-original-commit: e098e344d6307fb13cb53e776b4ecb1d71c2cc8c
Signed-off-by: Xavier Dollé (xdo) <xdo@odoo.com>
Signed-off-by: Pierre Paridans (app) <app@odoo.com>